variable "name" {}
variable "key_name" {}
variable "region" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "subnet_ids" {}
variable "availability_zones" {}
variable "domain_name" {}
variable "route53_zone_id" {}
